### PR TITLE
fix richmenu alias api type & add postback params

### LINKED ISSUE #290: Support Rich menu aliases Rich menu switch action apis
News: https://developers.line.biz/en/news/2021/06/21/switch-between-multiple-rich-menus/

### PR DESCRIPTION
**Pull request by xingoxu**
close #290

### CODE REVIEW

**Review by 4geru — APPROVED** [review]
thanks follow my missing place... 🙇

File: lib/types.ts [hunk 1]
```diff
@@ -2620,6 +2635,15 @@ export type MembersCountResponse = {
...
 };
 
+export type GetRichMenuAliasResponse = {
+  richMenuAliasId: string;
+  richMenuId: string;
+};
+
+export type GetRichMenuAliasListResponse = {
+  aliases: GetRichMenuAliasResponse[];
+};
```
Comment (spring-raining) [inline lib/types.ts:2645]: nitpick: seems more gentle if would set comments!

```suggestion
/**
 * @see [Get rich menu alias information](https://developers.line.biz/en/reference/messaging-api/#get-rich-menu-alias-by-id)
 */
export type GetRichMenuAliasResponse = {
  richMenuAliasId: string;
  richMenuId: string;
};

/**
 * @see [Get list of rich menu alias](https://developers.line.biz/en/reference/messaging-api/#get-rich-menu-alias-list)
 */
export type GetRichMenuAliasListResponse = {
  aliases: GetRichMenuAliasResponse[];
};
```

**Review by spring-raining — APPROVED** [review]

File: lib/types.ts (hunk 1 above)
Comment (xingoxu) [reply lib/types.ts:2682]: I forgot it! I'll do it in next time.
